# Generated by Django 3.2.9 on 2021-11-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('dsuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageurl', models.EmailField(max_length=256, verbose_name='이미지 주소')),
                ('contents', models.TextField(verbose_name='내용')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('tags', models.ManyToManyField(to='tag.Tag', verbose_name='태그')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsuser.dsuser', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '장고스타그램 게시물',
                'verbose_name_plural': '장고스타그램 게시물',
                'db_table': 'djangostagram_post',
            },
        ),
    ]
