# Generated by Django 3.2.9 on 2021-11-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageurl',
            field=models.CharField(max_length=512, verbose_name='이미지 주소'),
        ),
    ]
