# Generated by Django 3.2.9 on 2021-11-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dsuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=64, verbose_name='아이디')),
                ('useremail', models.EmailField(max_length=128, verbose_name='이메일')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
            ],
            options={
                'verbose_name': '장고스타그램 사용자',
                'verbose_name_plural': '장고스타그램 사용자',
                'db_table': 'djangostagram_dsuser',
            },
        ),
    ]
